[package]
name = "coda_ptc"
version = "0.1.0"
edition = "2024"

[dependencies]
coda_core = { workspace = true }
rquickjs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
